CXXFLAGS =	-O2 -g -Wall -fmessage-length=0

OBJS =	
LIBS =

TARGET =	root_overlay

.PHONY: root_overlay clean

#$(TARGET):	$(OBJS)
#	$(CXX) -o $(TARGET) $(OBJS) $(LIBS)

all:	$(TARGET)

clean:
	


root_overlay:
	