/*
 * winstar.h
 *
 *  Created on: 06/gen/2016
 *      Author: daniele
 */

#ifndef WINSTAR_H_
#define WINSTAR_H_
#include <stdint.h>


#define WINSTAR_I2C_ADD                 0x3e


#define WSTAR_CLEAR_DISPLAY_CMD             0x01
#define WSTAR_RETURN_HOME_CMD               0x02

#define WSTAR_ENTRY_MODE_SHIFT_ON			0x01
#define WSTAR_ENTRY_MODE_RIGHT				0x02
#define WSTAR_ENTRY_MODE_CMD				0x04

#define WSTAR_DISPLAY_BLINK					0x01
#define WSTAR_DISPLAY_CURSOR				0x02
#define WSTAR_DISPLAY_STATE					0x04
#define WSTAR_DISPLAY_CMD					0x08

#define WSTAR_CUR_DPY_SHIFT_RIGHT			0x04
#define WSTAR_CUR_DPY_SHIFT_SCREEN			0x08
#define WSTAR_CUR_DPY_SHIFT_CMD				0x10

#define WSTAR_FUNCTION_EXTENDED				0x01
#define WSTAR_FUNCTION_ONE_LINE_5X8_MASK	0x0C	// Reset bitmap
#define WSTAR_FUNCTION_ONE_LINE_5X16		0x04
#define WSTAR_FUNCTION_TWO_LINE_5X8			0x08
#define WSTAR_FUNCTION_8BIT					0x10
#define WSTAR_FUNCTION_CMD					0x20
#define WSTAR_CGRAM_ADD_MASK				0x3F
#define WSTAR_CGRAM_CMD						0x40
#define WSTAR_DDRAM_ADD_MASK				0x7F
#define WSTAR_DDRAM_CMD						0x80

#define WSTAR_BIAS_OSC_FREQ_MASK			0x07
#define WSTAR_BIAS_OSC_BIAS_1_4				0x08
#define WSTAR_BIAS_OSC_CMD					0x10

#define WSTAR_ICON_RAM_ADD_MASK				0x0F
#define WSTAR_ICON_RAM_ADD_CMD				0x40

#define WSTAR_POW_ICON_CONTRAST_CNTH_MASK	0x03
#define WSTAR_POW_ICON_CONTRAST_BOOST		0x04
#define WSTAR_POW_ICON_CONTRAST_ICON		0x08
#define WSTAR_POW_ICON_CONTRAST_CMD			0x50

#define WSTAR_FOLLOWER_RATIO_MASK			0x07
#define WSTAR_FOLLOWER_ON					0x08
#define WSTAR_FOLLOWER_CMD					0x60

#define WSTAR_CONTRAST_LOW_MASK				0x0F
#define WSTAR_CONTRAST_LOW_CMD				0x70




#define CONTRAST_DEFAULT                0x04
#define FOLLOWER_DEFAULT                0x07
#define CONTRAST_MAX					0x3f


#endif /* WINSTAR_H_ */
